### PR TITLE
Apply redirect to gallery cards

### PR DESCRIPTION
**Pull request by chillerno1**
Resolves https://github.com/martinyis/RepoAppIdea/issues/64

_Currently, the Project card in the project gallery has a hover effect, but when clicked, it does not perform any action. The actual link is only displayed for the repository name, but it should be displayed for the entire card. This way, when a user clicks on the card, they will be redirected to the project's repository._
- I've wrapped the ProjectCard components in a Link component that redirects to the Github repository.
- Validated that the existing links (repo/author) still work as expected after the change.

### CODE REVIEW

**Comment by martinyis** [comment]
There is bug, when a user is logged in they have abbility to click on star, when the star is clicked it still redirects to the github repo. When the user clicks on the star it should only star and should not redirect user anywehre.

**Comment by chillerno1** [comment]
@martinyis thanks for picking up that bug, I've added preventDefault to the click event on that like button to stop the redirect when it's clicked.

**Comment by martinyis** [comment]
@chillerno1 Somethign happened to the height of second card. Could you fix that?
image

**Comment by chillerno1** [comment]
@martinyis this should now behave and display as expected.

**Pull request merged**
