### PR TITLE
#55 done

### PR DESCRIPTION
**Pull request by web-dev-kushal**
image

### CODE REVIEW

**Comment by martinyis** [comment]
It looks pretty good but you need to change the path to reletive, below is a picture and work a bit on responsivness. But overall it is very nice, i like it. As soon as you fix path and reponsivness I am merging this pr!

image
image

**Comment by web-dev-kushal** [comment]
do you want the styling position: "relative" in css??

**Comment by web-dev-kushal** [comment]
Changes Done!!

**Comment by martinyis** [comment]
@web-dev-kushal Good work, merging!

**Pull request merged**
