### PR TITLE
Fixed navbar alignment

### PR DESCRIPTION
**Pull request by harshsbhandari**
Fixed - Misaligned Navbar in GitHub Repository #8
Added space on the left of the 'About' option in the navbar.

### CODE REVIEW

**Comment by harshsbhandari** [comment]
> @harshsbhandari Everything looks good. Could you just get rid of auto-formatting and I will merge this pr after!

@martinyis  Can you please explain what is  auto-formatting

**Comment by martinyis** [comment]
> Author

Take a look your commit file and you will see that you changed a bunch of lines not even knowing that. That was job of your code editor

**Comment by harshsbhandari** [comment]
> > Author
> 
> Take a look your commit file and you will see that you changed a bunch of lines not even knowing that. That was job of your code editor

@martinyis  Fixed auto formatting.

**Comment by martinyis** [comment]
> > > Author
> > 
> > 
> > Take a look your commit file and you will see that you changed a bunch of lines not even knowing that. That was job of your code editor
> 
> @martinyis Fixed auto formatting.

@harshsbhandari  Good work, merging this pr. Take a look at other issues!

**Pull request merged**
